// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sabemi.Infrastructure.Persistence;

#nullable disable

namespace Sabemi.Infrastructure.Migrations
{
    [DbContext(typeof(SabemiDbContext))]
    partial class SabemiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dotnet")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sabemi.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.ToTable("users", "dotnet");
                });

            modelBuilder.Entity("Sabemi.Domain.Entities.ContractStatus", b =>
                {
                    b.Property<string>("IdContrato")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id_contrato");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<int>("PagamentosConfirmados")
                        .HasColumnType("integer")
                        .HasColumnName("pagamentos_confirmados");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("situacao");

                    b.Property<string>("UltimaTransacao")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ultima_transacao");

                    b.Property<DateTimeOffset?>("UltimoPagamentoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_pagamento_em");

                    b.Property<decimal>("ValorTotalLiquidado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_total_liquidado");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("IdContrato");

                    b.ToTable("contract_statuses", "dotnet");
                });

            modelBuilder.Entity("Sabemi.Domain.Entities.LoginRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<string>("MagicTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("magic_token_hash");

                    b.Property<string>("OtpCodeHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("otp_code_hash");

                    b.Property<int>("OtpTentativas")
                        .HasColumnType("integer")
                        .HasColumnName("otp_tentativas");

                    b.Property<string>("Selector")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("selector");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_login_requests_email");

                    b.HasIndex("ExpiraEm")
                        .HasDatabaseName("ix_login_requests_expira_em");

                    b.HasIndex("MagicTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_login_requests_magic_token_hash");

                    b.HasIndex("Selector")
                        .IsUnique()
                        .HasDatabaseName("ux_login_requests_selector");

                    b.ToTable("login_requests", "dotnet");
                });

            modelBuilder.Entity("Sabemi.Domain.Entities.PaymentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AssinaturaVerificada")
                        .HasColumnType("boolean")
                        .HasColumnName("assinatura_verificada");

                    b.Property<DateTimeOffset?>("DataPagamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_pagamento");

                    b.Property<string>("Erro")
                        .HasColumnType("text")
                        .HasColumnName("erro");

                    b.Property<string>("IdContrato")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id_contrato");

                    b.Property<string>("IdTransacao")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("id_transacao");

                    b.Property<string>("PayloadBruto")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_bruto");

                    b.Property<DateTimeOffset?>("ProcessadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processado_em");

                    b.Property<DateTimeOffset>("RecebidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recebido_em");

                    b.Property<string>("StatusOrigem")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status_origem");

                    b.Property<string>("StatusProcessamento")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status_processamento");

                    b.Property<int>("Tentativas")
                        .HasColumnType("integer")
                        .HasColumnName("tentativas");

                    b.Property<decimal?>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("IdContrato")
                        .HasDatabaseName("ix_payment_events_id_contrato");

                    b.HasIndex("IdTransacao")
                        .IsUnique()
                        .HasDatabaseName("ux_payment_events_id_transacao");

                    b.HasIndex("StatusProcessamento", "RecebidoEm")
                        .HasDatabaseName("ix_payment_events_status_recebido");

                    b.ToTable("payment_events", "dotnet");
                });

            modelBuilder.Entity("Sabemi.Domain.Entities.ProcessingJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTimeOffset>("DisponivelEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("disponivel_em");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("estado");

                    b.Property<int>("MaxTentativas")
                        .HasColumnType("integer")
                        .HasColumnName("max_tentativas");

                    b.Property<Guid>("PaymentEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_event_id");

                    b.Property<DateTimeOffset?>("ReivindicadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reivindicado_em");

                    b.Property<string>("ReivindicadoPor")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("reivindicado_por");

                    b.Property<int>("Tentativas")
                        .HasColumnType("integer")
                        .HasColumnName("tentativas");

                    b.Property<string>("UltimoErro")
                        .HasColumnType("text")
                        .HasColumnName("ultimo_erro");

                    b.HasKey("Id");

                    b.HasIndex("PaymentEventId")
                        .IsUnique()
                        .HasDatabaseName("ux_processing_jobs_payment_event_id");

                    b.HasIndex("Estado", "DisponivelEm")
                        .HasDatabaseName("ix_processing_jobs_estado_disponivel");

                    b.ToTable("processing_jobs", "dotnet");
                });

            modelBuilder.Entity("Sabemi.Domain.Entities.ProcessingJob", b =>
                {
                    b.HasOne("Sabemi.Domain.Entities.PaymentEvent", "PaymentEvent")
                        .WithMany()
                        .HasForeignKey("PaymentEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentEvent");
                });
#pragma warning restore 612, 618
        }
    }
}
